name: greenway_commerce
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- AUTHENTICATION / FIREBASE ---
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  pin_code_fields: ^8.0.1
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.1
  firebase_app_check: ^0.3.2+9
  flutter_secure_storage: ^9.2.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6
  flutter_dotenv: ^5.2.1
  # flutter_facebook_auth: ^6.0.4

  #----------------- UTILITIES PACKAGES
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  #ßflutter_vibrate: ^1.3.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1

  # --- FILES / MEDIA ---
  image_picker: ^1.1.2
  file_picker: ^10.2.0

  # --- UI / ICONS ---
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.1
  animated_splash_screen: ^1.3.0

  #-------------- STATE MANAGEMENT
  get: ^4.6.6
  get_storage: ^2.1.1

  # --- TOASTS / ALERTS ---
  fluttertoast: ^8.2.12

  # PRODUCT SPECIFIC PACKAGES
  # Add any product-specific packages here

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/onboarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.otf
          style: italic
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 800
